### ISSUE TITLE
Sample Model

### ISSUE THREAD

**Issue by Immortalin** [Stockflare/trade-it#5]
Do you think a sample ActiveRecord model for an User object can be provided?

**Comment by stratmm** [comment]
Hi @Immortalin,

We don't actually have a user model as such.  Users in our system are handled externally with AWS cognito.  The only concept of user we have is the `identity` field, this is a GUID like string that can be regarded as a unique user id

**Comment by Immortalin** [comment]
So all processing of user data and brokerage connections are effectively stateless?
